version: "3.2"

services:
  db:
    image: postgres:14
    restart: always
    container_name: image-storage-db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
